<a href="https://colab.research.google.com/github/12Venky/first/blob/main/Movie_Rating_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import the required libraries**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

**Load the dataset**

In [ ]:
data=pd.read_csv('/content/IMDb Movies India.csv',encoding='latin')
data.head()

Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama   
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama   
2                         #Homecoming  (2021)   90 min   Drama, Musical   
3                             #Yaaram  (2019)  110 min  Comedy, Romance   
4                   ...And Once Again  (2010)  105 min            Drama   

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal   
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande   
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur   
3     4.4    35          Ovais Khan       Prateik          Ishita Raj   
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta   

           Actor 3  
0  Rajendra Bhatia  
1    Arvind Jangid  
2       Roy Angana  
3  Siddhant Kapoor  
4      Antara Mali

**Data Preprocessing**

In [ ]:
data.shape # This will return the shape of dataset

(15509, 10)

In [ ]:
data.info() # This will return the data type and non-null count of features

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      15509 non-null  object 
 1   Year      14981 non-null  object 
 2   Duration  7240 non-null   object 
 3   Genre     13632 non-null  object 
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object 
 6   Director  14984 non-null  object 
 7   Actor 1   13892 non-null  object 
 8   Actor 2   13125 non-null  object 
 9   Actor 3   12365 non-null  object 
dtypes: float64(1), object(9)
memory usage: 1.2+ MB


In [ ]:
data.describe(include=['object','float64'])

Name    Year Duration  Genre       Rating Votes      Director  \
count   15509   14981     7240  13632  7919.000000  7920         14984   
unique  13838     102      182    485          NaN  2034          5938   
top     Mamta  (2019)  120 min  Drama          NaN     8  Jayant Desai   
freq        7     410      240   2780          NaN   227            58   
mean      NaN     NaN      NaN    NaN     5.841621   NaN           NaN   
std       NaN     NaN      NaN    NaN     1.381777   NaN           NaN   
min       NaN     NaN      NaN    NaN     1.100000   NaN           NaN   
25%       NaN     NaN      NaN    NaN     4.900000   NaN           NaN   
50%       NaN     NaN      NaN    NaN     6.000000   NaN           NaN   
75%       NaN     NaN      NaN    NaN     6.800000   NaN           NaN   
max       NaN     NaN      NaN    NaN    10.000000   NaN           NaN   

            Actor 1 Actor 2 Actor 3  
count         13892   13125   12365  
unique         4718    4891    4820  
top     Ashok Kumar   Rekha    Pran  
freq            158      83      91  
mean            NaN     NaN     NaN  
std             NaN     NaN     NaN  
min             NaN     NaN     NaN  
25%             NaN     NaN     NaN  
50%             NaN     NaN     NaN  
75%             NaN     NaN     NaN  
max             NaN     NaN     NaN

In [ ]:
data.isna().sum()  # As we have more missing values we don't drop them ,we have to replce them

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(6)

In [ ]:
data.drop_duplicates(inplace=True) #Removing duplicates

In [ ]:
data['Duration'].unique()

array([nan, '109 min', '90 min', '110 min', '105 min', '147 min',
       '142 min', '59 min', '82 min', '116 min', '96 min', '120 min',
       '161 min', '166 min', '102 min', '87 min', '132 min', '66 min',
       '146 min', '112 min', '168 min', '158 min', '126 min', '94 min',
       '138 min', '124 min', '144 min', '157 min', '136 min', '107 min',
       '113 min', '80 min', '122 min', '149 min', '148 min', '130 min',
       '121 min', '188 min', '115 min', '103 min', '114 min', '170 min',
       '100 min', '99 min', '140 min', '128 min', '93 min', '125 min',
       '145 min', '75 min', '111 min', '134 min', '85 min', '104 min',
       '92 min', '137 min', '127 min', '150 min', '119 min', '135 min',
       '86 min', '76 min', '70 min', '72 min', '151 min', '95 min',
       '52 min', '89 min', '143 min', '177 min', '117 min', '123 min',
       '154 min', '88 min', '175 min', '153 min', '78 min', '139 min',
       '133 min', '101 min', '180 min', '60 min', '46 min', '164 min',
       '

In [ ]:
data['Year'].unique()

array([nan, '(2019)', '(2021)', '(2010)', '(1997)', '(2005)', '(2008)',
       '(2012)', '(2014)', '(2004)', '(2016)', '(1991)', '(1990)',
       '(2018)', '(1987)', '(1948)', '(1958)', '(2017)', '(2020)',
       '(2009)', '(2002)', '(1993)', '(1946)', '(1994)', '(2007)',
       '(2013)', '(2003)', '(1998)', '(1979)', '(1951)', '(1956)',
       '(1974)', '(2015)', '(2006)', '(1981)', '(1985)', '(2011)',
       '(2001)', '(1967)', '(1988)', '(1995)', '(1959)', '(1996)',
       '(1970)', '(1976)', '(2000)', '(1999)', '(1973)', '(1968)',
       '(1943)', '(1953)', '(1986)', '(1983)', '(1989)', '(1982)',
       '(1977)', '(1957)', '(1950)', '(1992)', '(1969)', '(1975)',
       '(1947)', '(1972)', '(1971)', '(1935)', '(1978)', '(1960)',
       '(1944)', '(1963)', '(1940)', '(1984)', '(1934)', '(1955)',
       '(1936)', '(1980)', '(1966)', '(1949)', '(1962)', '(1964)',
       '(1952)', '(1933)', '(1942)', '(1939)', '(1954)', '(1945)',
       '(1961)', '(1965)', '(1938)', '(1941)', '(1931)', 

In [ ]:
data['Votes'].unique()

array([nan, '8', '35', ..., '70,344', '408', '1,496'], dtype=object)

**Handling Missing Values**

In [ ]:
missing_percentage = (data.isnull().sum() / len(data)) * 100
print(missing_percentage)

Name         0.000000
Year         3.399342
Duration    53.305812
Genre       12.100884
Rating      48.919564
Votes       48.913114
Director     3.379991
Actor 1     10.417339
Actor 2     15.358318
Actor 3     20.254144
dtype: float64


In [ ]:
threshold = 50   # dropping based on the threshold value i.e half missing values
columns_to_drop = missing_percentage[missing_percentage > threshold].index
data.drop(columns=columns_to_drop, inplace=True)
print(f"Dropped columns: {columns_to_drop}")

Dropped columns: Index(['Duration'], dtype='object')


In [ ]:
data['Year'] = data['Year'].astype(str).str.replace(r'[^0-9]', '', regex=True)
data['Year'] = pd.to_numeric(data['Year'], errors='coerce')
data.fillna({'Year':0}, inplace=True)
data['Year'] = data['Year'].astype(int)

In [ ]:
data['Year']

0           0
1        2019
2        2021
3        2019
4        2010
         ... 
15504    1988
15505    1999
15506    2005
15507    1988
15508    1998
Name: Year, Length: 15503, dtype: int64

In [ ]:
data.fillna({'Rating':0}, inplace=True)
data['Votes'] = data['Votes'].astype(str).str.replace(',', '', regex=True)
data['Votes'] = pd.to_numeric(data['Votes'], errors='coerce')
data.fillna({'Votes':0}, inplace=True)

In [ ]:
numerical_columns = ['Year', 'Votes', 'Rating']
for col in numerical_columns:
    data[col] = pd.to_numeric(data[col], errors='coerce')
    data.fillna({col:data[col].median()}, inplace=True)

# Check for remaining NaNs in numerical columns
print("Remaining NaNs in numerical columns:")
print(data[numerical_columns].isnull().sum())

Remaining NaNs in numerical columns:
Year      0
Votes     0
Rating    0
dtype: int64


**Removing Outliers**

In [ ]:
q1 = data['Votes'].quantile(0.25)
q3 = data['Votes'].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

data = data[(data['Votes'] >= lower_bound) & (data['Votes'] <= upper_bound)]

**Encoding Categorical Values**

In [ ]:
# Handle missing values in categorical columns
categorical_columns = ['Genre', 'Actor 1', 'Actor 2', 'Actor 3', 'Director']
for col in categorical_columns:
    data.fillna({col:'Unknown'}, inplace=True)

# Replace rare categories with 'Other'
top_n = 20
for col in categorical_columns:
    top_categories = data[col].value_counts().nlargest(top_n).index
    data[col] = data[col].apply(lambda x: x if x in top_categories else 'Other')

# Feature Engineering
data['Director_Avg_Rating'] = data.groupby('Director')['Rating'].transform('mean')
actor_1_popularity = data.groupby('Actor 1').size().rename('Actor_1_Popularity')
data = data.merge(actor_1_popularity, on='Actor 1', how='left')

# Handle missing values using median
categorical_columns = ['Genre', 'Actor 1', 'Actor 2', 'Actor 3', 'Director']
for col in categorical_columns:
    data.fillna({col:'Unknown'}, inplace=True)

top_n = 20
for col in categorical_columns:
    top_categories = data[col].value_counts().nlargest(top_n).index
    data[col] = data[col].apply(lambda x: x if x in top_categories else 'Other')

data.loc[:,'Director_Avg_Rating'] = data.groupby('Director')['Rating'].transform('mean')
data.loc[:,'Actor_1_Popularity'] = data.groupby('Actor 1')['Actor 1'].transform('count')

# Handle missing values
data.fillna({'Director_Avg_Rating':data['Director_Avg_Rating'].median()}, inplace=True)
data.fillna({'Actor_1_Popularity':data['Actor_1_Popularity'].median()}, inplace=True)

# One-Hot Encoding using pd.get_dummies
encoded_data = pd.get_dummies(data[categorical_columns], drop_first=False)

# Concatenate encoded columns and drop original columns
data = pd.concat([data, encoded_data], axis=1).drop(categorical_columns, axis=1)

print("Data Preprocessing Complete! Shape:", data.shape)


Data Preprocessing Complete! Shape: (12682, 106)


In [ ]:
# Select relevant features
X = data[['Year', 'Votes', 'Director_Avg_Rating', 'Actor_1_Popularity']]
y = data['Rating']

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.80)  # Retain 80% of the variance
X_pca_reduced = pca.fit_transform(X_scaled)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X_pca_reduced, y, test_size=0.2, random_state=42) # Splitting train and test dataset

In [ ]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.7388753300425583
R-squared: 0.9136015999242862


In [ ]:
#Evaluate on Train data
y_train_pred = model.predict(x_train)
train_r2 = r2_score(y_train, y_train_pred)
print(f'Training R²: {train_r2}')

# Evaluate on test data
test_r2 = r2_score(y_test, y_pred)
print(f'Test R²: {test_r2}')

Training R²: 0.9778426375771139
Test R²: 0.9136015999242862


In [ ]:
# Perform 5-fold cross-validation
scores = cross_val_score(model, X, y, cv=5, scoring='r2')
print(f'Cross-Validation R² Scores: {scores}')
print(f'Mean R²: {scores.mean()}')

Cross-Validation R² Scores: [0.92729743 0.9280047  0.9178742  0.92582205 0.92348537]
Mean R²: 0.9244967499745623
